version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-node
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379
    networks:
      - data-node

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    volumes:
      - redis-data:/data
    networks:
      - data-node

networks:
  data-node:

volumes:
  redis-data:
